### ISSUE TITLE
Java 8 build test

### ISSUE THREAD

**Issue by geobotmatico** [geoladris/geoladris#20]
Test the packaging process with Java 8. We had the problem solved with this link and code:

http://stackoverflow.com/questions/15886209/maven-is-not-working-in-java-8-when-javadoc-tags-are-incomplete#16743137

           <configuration>
               <additionalparam>-Xdoclint:none</additionalparam>
           </configuration>
en la línea 60 del pom.xml de core

**Comment by victorzinho** [comment]
I'm not able to reproduce it; it shows warnings for wrong Javadocs, but the build succeeds.
@michogar Can you still reproduce it?

Here my Maven version:
```
$ mvn -version
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T18:29:23+01:00)
Maven home: /home/vicgonco/bin/apache-maven-3.2.5
Java version: 1.8.0_91, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-63-generic", arch: "amd64", family: "unix"
$ mvn package
```

**Comment by michogar** [comment]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] geoladris core - parent ............................ SUCCESS [  2.822 s]
[INFO] jwebclient-analyzer ................................ SUCCESS [  4.693 s]
[INFO] geoladris core ..................................... FAILURE [  3.147 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11.123 s
[INFO] Finished at: 2016-09-23T12:39:49+02:00
[INFO] Final Memory: 26M/357M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.4:jar (attach-javadocs) on project core: MavenReportException: Error while generating Javadoc:
[ERROR] Exit code: 1 - /home/michogarcia/geomati.co/FAO/dev/geoladris/core/core/src/main/java/org/fao/unredd/portal/Config.java:54: warning: no description for @param
[ERROR] * @param property
[ERROR] ^
[ERROR] /home/michogarcia/geomati.co/FAO/dev/geoladris/core/core/src/main/java/org/fao/unredd/portal/Config.java:55: warning: no description for @return
[ERROR] * @return
[ERROR] ^
[ERROR] /home/michogarcia/geomati.co/FAO/dev/geoladris/core/core/src/main/java/org/fao/unredd/portal/Config.java:71: warning: no description for @param
[ERROR] * @param locale
[ERROR] ^
[ERROR] /home/michogarcia/geomati.co/FAO/dev/geoladris/core/core/src/main/java/org/fao/unredd/portal/Config.java:72: warning: no description for @param
[ERROR] * @param request
[ERROR] ^
[ERROR] /home/michogarcia/geomati.co/FAO/dev/geoladris/core/core/src/main/java/org/fao/unredd/portal/Config.java:73: warning: no description for @return
[ERROR] * @return
[ERROR] ^
[ERROR] /home/michogarcia/geomati.co/FAO/dev/geoladris/core/core/src/main/java/org/fao/unredd/portal/Config.java:79: error: reference not found
[ERROR] * {@link #getPluginConfiguration(HttpServletRequest)} and
[ERROR] ^
[ERROR] /home/michogarcia/geomati.co/FAO/dev/geoladris/core/core/src/main/java/org/fao/unredd/portal/Config.java:81: warning: no description for @param
[ERROR] * @param provider
[ERROR] ^
[ERROR] /home/michogarcia/geomati.co/FAO/dev/geoladris/core/core/src/main/java/org/fao/unredd/portal/Config.java:89: warning: no description for @return
[ERROR] * @return
[ERROR] ^
[ERROR] /home/michogarcia/geomati.co/FAO/dev/geoladris/core/core/src/main/java/org/fao/unredd/portal/Config.java:83: warning - Tag @link: can't find getPluginConfiguration(HttpServletRequest) in org.fao.unredd.portal.Config
[ERROR] /home/michogarcia/geomati.co/FAO/dev/geoladris/core/core/src/main/java/org/fao/unredd/portal/ConfigurationProviderHelper.java:39: error: reference not found
[ERROR] *            {@link #PublicConfHelper(JSONContentProvider, Map)}.
[ERROR] ^
[ERROR] /home/michogarcia/geomati.co/FAO/dev/geoladris/core/core/src/main/java/org/fao/unredd/portal/ConfigurationProviderHelper.java:47: error: reference not found
[ERROR] *             {@link #ConfigurationProviderHelper(JSONContentProvider, Map)}
[ERROR] ^
[ERROR] /home/michogarcia/geomati.co/FAO/dev/geoladris/core/core/src/main/java/org/fao/unredd/portal/ConfigurationProviderHelper.java:50: warning - Tag @link: can't find PublicConfHelper(JSONContentProvider, Map) in org.fao.unredd.portal.ConfigurationProviderHelper
[ERROR] /home/michogarcia/geomati.co/FAO/dev/geoladris/core/core/src/main/java/org/fao/unredd/portal/ConfigurationProviderHelper.java:50: warning - Tag @link: can't find ConfigurationProviderHelper(JSONContentProvider, Map) in org.fao.unredd.portal.ConfigurationProviderHelper
[ERROR] /home/michogarcia/geomati.co/FAO/dev/geoladris/core/core/src/main/java/org/fao/unredd/portal/DefaultConfig.java:75: warning: no description for @return
[ERROR] * @return
[ERROR] ^
[ERROR] /home/michogarcia/geomati.co/FAO/dev/geoladris/core/core/src/main/java/org/fao/unredd/portal/ModuleConfigurationProvider.java:21: warning: no description for @param
[ERROR] * @param configurationContext
[ERROR] ^
[ERROR] /home/michogarcia/geomati.co/FAO/dev/geoladris/core/core/src/main/java/org/fao/unredd/portal/ModuleConfigurationProvider.java:25: warning: no description for @return
[ERROR] * @return
[ERROR] ^
[ERROR] /home/michogarcia/geomati.co/FAO/dev/geoladris/core/core/src/main/java/org/fao/unredd/portal/ModuleConfigurationProvider.java:26: warning: no description for @throws
[ERROR] * @throws IOException
[ERROR] ^
[ERROR] /home/michogarcia/geomati.co/FAO/dev/geoladris/core/core/src/main/java/org/fao/unredd/portal/ModuleConfigurationProvider.java:34: error: reference not found
[ERROR] * {@link #getConfigurationMap(PortalRequestConfiguration, HttpServletRequest)}
[ERROR] ^
[ERROR] /home/michogarcia/geomati.co/FAO/dev/geoladris/core/core/src/main/java/org/fao/unredd/portal/ModuleConfigurationProvider.java:37: warning: no description for @return
[ERROR] * @return
[ERROR] ^
[ERROR] /home/michogarcia/geomati.co/FAO/dev/geoladris/core/core/src/main/java/org/fao/unredd/portal/ModuleConfigurationProvider.java:39: warning - Tag @link: can't find getConfigurationMap(PortalRequestConfiguration, HttpServletRequest) in org.fao.unredd.portal.ModuleConfigurationProvider
[ERROR] /home/michogarcia/geomati.co/FAO/dev/geoladris/core/core/src/main/java/org/fao/unredd/portal/PortalRequestConfiguration.java:20: warning: no description for @return
[ERROR] * @return
[ERROR] ^
[ERROR] 
[ERROR] Command line was: /usr/lib/jvm/java-8-oracle/jre/../bin/javadoc @options @packages
[ERROR] 
[ERROR] Refer to the generated Javadoc files in '/home/michogarcia/geomati.co/FAO/dev/geoladris/core/core/target/apidocs' dir.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :core

**Comment by michogar** [comment]
Si quito esas lineas del pom.xml a mi me da error:

michogarcia@michomatico:~/geomati.co/FAO/dev/geoladris/core$ mvn --version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
Maven home: /usr/share/maven
Java version: 1.8.0_101, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: es_ES, platform encoding: UTF-8
OS name: "linux", version: "3.16.0-4-amd64", arch: "amd64", family: "unix"

**Comment by victorzinho** [comment]
Fallaba para Java 1.8.0_101 pero no para 1.8.0_91...
